### ISSUE TITLE
Line 153 in 01_proc-struc_volumetric allows run_first_all to be prematurely terminated 

### ISSUE THREAD

**Issue by MarkNelson86** [MICA-LAB/micapipe#6]
Hi all, 

  I believe this conditional allows the code to advance & the file names to be changed before run_first_all is complete.

**run_first_all** does the following:
(1) calls first_flirt
(2) calls run_first & first_boundary_corr for each subcortical region
(3) calls fslmerge twice. Once to compile all the *corr* files into the 4D *firstseg* file, and again to compile all the *first* files into the 4D *origsegs* file. 
(4) calls to first_mult_bcorr to convert *firstseg* into a 3D file with all subcortical segmentations together. This is the final version of *firstseg* that is later copied in line 115 of post_structural and eventually used to compute subcortical connectomes.
(5) calls to imrm to remove all of the individual segmentation files (*corr* & *first*)

  The intermediate 4D version of *firstseg* created by the first call to fslmerge has the same name. This allows the code to advance prematurely and run_first_all to be interrupted before the final version is computed. At least on the BIC cluster this is happening.

Thanks for the great pipeline!
Mark

**Comment by rcruces** [comment]
Hi Mark,

Thanks for the observation, could you share me the outputs located on <subject_dir>/proc_struct/first please. We've also run this on the BIC cluster and I found two different outputs:
<>_nativepro_all_fast_origsegs.nii.gz a 4D files with 15 segmentations
<>_nativepro_all_fast_firstseg.nii.gz the 3D file with all the segmentations merged
plus the .btk and .bvars files

We are still fixing minor issues before the big release, so if you find something else don hesitate to contact us.

best

Raul

**Comment by MarkNelson86** [comment]
Hi Raul,

  Sure, my outputs are located at: 

  /data_/tardiflab/MICAdata_Nov2020/procLocal/sub-HC*/ses-01/proc_struct/first/ 

  on the BIC, or I've emailed you a google drive link if you prefer.

  When I ran the code on the cluster as is, 1 of 2 things happened:
(1) A 4D version of  *firstseg* would be generated, no *origsegs* would be generated, and fslmerge would throw an error indicating that its input files could not be found. 
(2) OR 4D versions of both *origsegs* & *firstseg* would be generated, but first_mult_bcorr would throw the error: **std::bad_alloc**. 

  As a quick fix I just extended the sleep timer to 5m to ensure *origsegs* is generated, and ran first_mult_bcorr locally to avoid the allocation error.

**Comment by rcruces** [comment]
Hello,

thanks for your feedback, I fixed that issue and test it on the BIC locally on mica.q and all.q and apparently worked. 
The resolution is on this commit:
https://github.com/MICA-LAB/micapipe/commit/9b16b80cf9f288f14383136b59c75627adde5936#diff-576fc9b3901537efe6366e50afb4e692d8795f871576f2e85440d33405b5deeb

best

**Comment by MarkNelson86** [comment]
Nice work! Thanks
________________________________
